### ISSUE TITLE
inconsistent use of the hamburger icon

### ISSUE THREAD

**Issue by octarino** [vpaliyX/Flash-MusicPlayer#2]
On the main screen you use the hamburger icon to open the drawer, but in the song screen is used to open the fragment_actions screen. On the other hand in the track list you use the overflow icon to get to the fragment_actions screen.

On the top right the hamburger icon looks like it would open a RTL drawer. 

I'd recommend changing it to the overflow icon, or a different one.

**Comment by vpaliyX** [comment]
The first commit should have been for #4
