### ISSUE TITLE
Recent empty state needs padding

### ISSUE THREAD

**Issue by octarino** [vpaliyX/Flash-MusicPlayer#3]
"You have not listened to anything so far"

https://github.com/vpaliyX/Flash-MusicPlayer/blob/1b45bae1e081fe26cf37778f45771e134ff71a3b/app/src/main/res/layout/fragment_home.xml#L18

![b71421df-ef18-4e1d-b7da-b7a57a3bba25](https://user-images.githubusercontent.com/22935424/31307383-752f1542-ab5b-11e7-963d-60af7949934c.jpg)

**Comment by vpaliyX** [comment]
I have added left/right margins to this.
