### ISSUE TITLE
wordding suggestion: change 'dislike' to 'unlike'

### ISSUE THREAD

**Issue by octarino** [vpaliyX/Flash-MusicPlayer#6]
Since the isn't a disliked songs list, a song either is on the liked list or it's not.

> (in the context of social media) withdraw one's approval of or support for (someone or something one has previously liked) by means of an icon or link.

To compare it to reddit: a liked song is upvoted, and an unliked song would be removing the upvote but not downvoting (disliking).

**Comment by vpaliyX** [comment]
That's a good point! Thank you.
